version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - youfin-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./youfin-be
      dockerfile: Dockerfile
    container_name: youfin-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/youfin
      - NODE_ENV=development
      - PORT=8000
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-dummy-key}
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./youfin-be:/app
      - backend_node_modules:/app/node_modules
    networks:
      - youfin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./youfin-fe
      dockerfile: Dockerfile
    container_name: youfin-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0
      - PORT=5173
    volumes:
      - ./youfin-fe:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - youfin-network
    restart: unless-stopped

volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules:

networks:
  youfin-network:
    driver: bridge 